#ifndef _S2E_PLUGINS_MEMORYACCESS_H
#define _S2E_PLUGINS_MEMORYACCESS_H

enum AccessType
{
    ACCESS_TYPE_READ = 0x1,
    ACCESS_TYPE_WRITE = 0x2,
    ACCESS_TYPE_EXECUTE = 0x4,
    ACCESS_TYPE_CONCRETE_VALUE = 0x8,
    ACCESS_TYPE_SYMBOLIC_VALUE = 0x10,
    ACCESS_TYPE_CONCRETE_ADDRESS = 0x20,
    ACCESS_TYPE_SYMBOLIC_ADDRESS = 0x40,
    ACCESS_TYPE_NON_IO = 0x80,
    ACCESS_TYPE_IO = 0x100,
    ACCESS_TYPE_SIZE_1 = 0x1000,
    ACCESS_TYPE_SIZE_2 = 0x2000,
    ACCESS_TYPE_SIZE_4 = 0x4000,
    ACCESS_TYPE_SIZE_8 = 0x8000,
    ACCESS_TYPE_SIZE_16 = 0x10000
};

static const int ACCESS_TYPE_SIZE_ANY = ACCESS_TYPE_SIZE_1
		| ACCESS_TYPE_SIZE_2
		| ACCESS_TYPE_SIZE_4
		| ACCESS_TYPE_SIZE_8
		| ACCESS_TYPE_SIZE_16;

#define BITSIZE_TO_ACCESS_TYPE_SIZE(x) \
	(((x) << 9) & 0x1f000)

#define BYTESIZE_TO_ACCESS_TYPE_SIZE(x) \
	(((x) << 12) & 0x1f000)

#endif /* _S2E_PLUGINS_MEMORYACCESS_H */
